### ISSUE TITLE
Consider adding the following

### ISSUE THREAD

**Issue by shatu** [metrofun/machine-learning-surveys#4]
Deep Learning
* (Tutorial) GANs https://arxiv.org/pdf/1701.00160.pdf
* (Tutorial) VAEs https://arxiv.org/pdf/1606.05908.pdf

NLP/Machine Translation
* (Tutorial) Neural Machine Translation https://arxiv.org/pdf/1703.01619.pdf

**Comment by metrofun** [comment]
🤝 Thanks. Great current topics with credible authors.
