### ISSUE TITLE
A few NLP papers...

### ISSUE THREAD

**Issue by ykumards** [metrofun/machine-learning-surveys#5]
Hello,

I had a few papers used as reference in an NLP class at NYU which you may consider adding.

* Goldberg, Yoav. "A primer on neural network models for natural language processing." Journal of Artificial Intelligence Research 57 (2016): 345-420. http://u.cs.biu.ac.il/~yogo/nnlp.pdf 
* Knight, Kevin. "A statistical MT tutorial workbook." (1999). https://www.isi.edu/natural-language/mt/wkbk.pdf

The course page had many more: http://cs.nyu.edu/courses/fall15/CSCI-GA.3033-008/

**Comment by metrofun** [comment]
Hi,

Cool, Thanks!
I'll immediately add "A primer on neural network models for natural language processing." and check the course page.

I can totally imagine that "A statistical MT tutorial workbook." is old but gold, however, for now, I'm trying to prioritize newer staff over the old 😊
